import supabaseClient from "@/utils/supabase";

interface Message {
  id?: string; // Make id optional since it will be generated by Supabase
  text: string;
  user_id: string;
  room: string;
  created_at: string;
  file_url?: string;
}

// Function to send a message
export const sendMessage = async (token: string,_, message: Omit<Message, 'id'>) => {
  const supabase = supabaseClient(token); // Initialize Supabase client with the token
  const { data, error } = await supabase
    .from('messages')
    .insert(message);

  if (error) {
    console.error('Error sending message:', error);
    throw error; // Rethrow the error for handling in the calling function
  }

  return data || []; // Return the inserted data or an empty array
};